export enum CrmFilterInputOperatorEnum {
  Eq = 'EQ',
  Neq = 'NEQ',
  Lt = 'LT',
  Lte = 'LTE',
  Gt = 'GT',
  Gte = 'GTE',
  Between = 'BETWEEN',
  In = 'IN',
  NotIn = 'NOT_IN',
  HasProperty = 'HAS_PROPERTY',
  NotHasProperty = 'NOT_HAS_PROPERTY',
  ContainsToken = 'CONTAINS_TOKEN',
  NotContainsToken = 'NOT_CONTAINS_TOKEN',
}
